select * from customer limit 20

--Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender

--Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_

--Q3. Which are the top 5 products with the highest average review rating?
--Q4. Compare the average Purchace Amounts between Standard and Express Shipping.
--Q5. Do subscribed customers spend more? Compare averaged spend and total revenue between subscribes and non-subscribes
--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
--Q8. What are the top 3 most purchased products within each category?
--Q9. Are customers who are repeat buyers (more than 5 previous purhaces) also likely to subscribe?
--Q10. What is the revenue contribution of each age group?